version: '3'

services:
  app:
    build: .
    entrypoint: /bin/fail
    command:
      - "-c"
      - "ENDPOINT=$$UFFIZZI_URL node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 8080

  continuous_preview:
    delete_preview_after: 10h
