version: '3'

services:
  app:
    image: nginx:latest
    volumes:
      - ./.dot_nginx:/usr/share/nginx/html/dot-nginx

x-uffizzi:
  ingress:
    service: app
    port: 80

  continuous_preview:
    delete_preview_after: 1h
